# Generated by Django 4.0.3 on 2022-04-07 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='authDivision',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d190cd84-6529-48ec-97e2-16352b3711c1'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b63c20e8-b857-43e5-b402-fff7ca3c81c4'), editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('548f60eb-569b-40bb-8515-2e2b2c9bc8e0'), editable=False, primary_key=True, serialize=False)),
                ('permission_uuid', models.ManyToManyField(to='approvalCard.permissions')),
            ],
        ),
        migrations.CreateModel(
            name='authUserDivision',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7a00ec15-f786-4349-bd07-7b889224e63e'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('division_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='approvalCard.authdivision')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='authUserCard',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5fb5f819-8abb-4180-a013-bc45881df1e6'), editable=False, primary_key=True, serialize=False)),
                ('card_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='approvalCard.cards')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
