# Generated by Django 4.0.3 on 2022-04-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvalCard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='card_uuid',
        ),
        migrations.AddField(
            model_name='cards',
            name='permission_uuid',
            field=models.ManyToManyField(blank=True, null=True, to='approvalCard.permissions'),
        ),
    ]
