# Generated by Django 4.0.3 on 2022-04-07 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('approvalCard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authdivision',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bfbb66f-c82b-432d-931d-0f0af1a6b0ea'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authusercard',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b5b6663-9d2b-4a78-9914-56057952c724'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authuserdivision',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92743461-3505-4bc2-9517-63df6a3961a1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cards',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c0ea6742-f19e-4126-b969-1690dc28d8f1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('31c00108-00cd-4705-9b7b-df0c83286d75'), editable=False, primary_key=True, serialize=False),
        ),
    ]
