# Generated by Django 4.0.3 on 2022-04-07 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('approvalCard', '0002_alter_authdivision_id_alter_authusercard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authdivision',
            name='id',
            field=models.UUIDField(default=uuid.UUID('244bd4c1-6b9f-40bd-bc4b-3d12f07895a2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authusercard',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6c2f2d01-b9dc-4b69-9b3c-a581901c474b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authuserdivision',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5cb09c36-d68e-4640-bd8d-ac74093af2f9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cards',
            name='id',
            field=models.UUIDField(default=uuid.UUID('86ec1f92-712f-4d7f-b006-859db7a48adf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7394ed43-27de-468a-91bc-587ded37a576'), editable=False, primary_key=True, serialize=False),
        ),
    ]
